version: '3'
services:
  mysql:
    image: mysql:8.0.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: w2w
      MYSQL_USER: strapi
      MYSQL_PASSWORD: root